main: main.cpp Common.o D2Map.o ArrayEx.o
	g++ main.cpp Common.o D2Map.o ArrayEx.o -o main

Common.o: Common.cpp
	g++  -w-c Common.cpp -o Common.o

D2Map.o: D2Map.cpp
	g++ -w -c D2Map.cpp -o D2Map.o

ArrayEx.o: ArrayEx.cpp
	g++ -w -c ArrayEx.cpp -o ArrayEx.o