Common: Common.cpp
	g++ Common.cpp -o Common.o

D2Map: D2Map.cpp
	g++ D2Map.cpp -o D2Map.o

ArrayEx: ArrayEx.cpp
	g++ ArrayEx.cpp -o ArrayEx.o

D2Map: D2Map.cpp
	g++ D2Map.cpp -o D2Map.o

D2Map: D2Map.cpp
	g++ D2Map.cpp -o D2Map.o

D2Map: D2Map.cpp
	g++ D2Map.cpp -o D2Map.o

D2Map: D2Map.cpp
	g++ D2Map.cpp -o D2Map.o
